<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: s-suzuki
 * Date: Sat, 28 Sep 2013 00:21:00 -0700
 */

$conf['title'] = '株式会社フクダ　オンラインマニュアル';
$conf['start'] = 'welcome';
$conf['lang'] = 'ja';
$conf['savedir'] = '/opt/bitnami/apps/dokuwiki/data';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['subscribers'] = 1;
$conf['notify'] = 's-suzuki@fukuda-web.jp';
$conf['registernotify'] = 's-suzuki@fukuda-web.jp';
$conf['mailfrom'] = 'info@fukuda-web.jp';
$conf['mailprefix'] = 'フクダオンラインマニュアル';
$conf['htmlmail'] = 0;
$conf['plugin']['swiftmail']['smtp_host'] = 'fukuda-web.jp';
$conf['plugin']['swiftmail']['smtp_port'] = 587;
$conf['plugin']['swiftmail']['smtp_ssl'] = '8';
$conf['plugin']['swiftmail']['auth_user'] = 's-suzuki@fukuda-web.jp';
$conf['plugin']['swiftmail']['auth_pass'] = 'fukuda1129';
$conf['plugin']['swiftmail']['debug'] = 1;

// end auto-generated content
