#!/bin/sh
     
# Japanese-environment
#apt install language-pack-ja-base language-pack-ja
#export LC_ALL=ja_JP.UTF-8

HOME=/
# vim
ln -s Settings/vim/.vimrc .vimrc
ln -s Settings/vim/.vim .vim
mkdir $HOME.vimswap
mkdir $HOME.vimbackup
git clone https://github.com/gmarik/vundle.git $HOME.vim/bundle/vundle
