#!/bin/sh
     
echo setting root password
sudo passwd root

echo setting timezone
sudo dpkg-reconfigure tzdata

# Japanese-environment
wget -q https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg -O- | sudo apt-key add -
wget -q https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg -O- | sudo apt-key add -
sudo wget https://www.ubuntulinux.jp/sources.list.d/precise.list -O /etc/apt/sources.list.d/ubuntu-ja.list
sudo apt-get update

# vim
ln -s Settings/vim/.vimrc .vimrc
ln -s Settings/vim/.vim .vim
mkdir ~/.vimswap
mkdir ~/.vimbackup
sudo apt-get install vim
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

# zsh
sudo apt-get install zsh
shpath=$(which zsh) 
chsh -s ${shpath}
ln -s Settings/zsh/.zshrc .zshrc
ln -s Settings/zsh/.zshenv .zshenv
ln -s Settings/zsh/.zsh_history .zsh_history
ln -s Settings/networK/satnet satnet
ln -s Settings/networK/fukudanet fukudanet
echo "PATH=/opt/bitnami/ruby/bin/:${PATH}" >> Settings/zsh/.zshrc

# enable ssh
sudo mv /etc/init/ssh.conf.back /etc/init/ssh.conf

