#!/bin/sh
     

# Japanese-environment
wget -q https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg -O- | sudo apt-key add -
wget -q https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg -O- | sudo apt-key add -
sudo wget https://www.ubuntulinux.jp/sources.list.d/precise.list -O /etc/apt/sources.list.d/ubuntu-ja.list
apt-get update -y

# vim
ln -s Settings/vim/.vimrc .vimrc
ln -s Settings/vim/.vim .vim
mkdir /home/satrex/.vimswap
mkdir /home/satrex/.vimbackup
git clone https://github.com/gmarik/vundle.git /home/satrex/.vim/bundle/vundle

# zsh
shpath=$(which zsh) 
chsh -s ${shpath}
ln -s Settings/zsh/.zshrc .zshrc
ln -s Settings/zsh/.zshenv .zshenv
ln -s Settings/zsh/.zsh_history .zsh_history
ln -s Settings/networK/satnet satnet
ln -s Settings/networK/fukudanet fukudanet
