#!/bin/sh
     
# Japanese-environment
#apt install language-pack-ja-base language-pack-ja
#export LC_ALL=ja_JP.UTF-8

HOME=/
# vim
ln -s Settings/vim/.vimrc .vimrc
ln -s Settings/vim/.vim .vim
mkdir $HOME.vimswap
mkdir $HOME.vimbackup

# vim plugin
git clone https://github.com/gmarik/Vundle.vim.git $HOME.vim/bundle/Vundle.vim

# set vim color scheme
git clone https://github.com/tomasr/molokai
mv molokai/colors/molokai.vim $HOME.vim/colors

