#!/bin/sh
     
echo setting root password
passwd root

# Japanese-environment
wget -q https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg -O- | sudo apt-key add -
wget -q https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg -O- | sudo apt-key add -
sudo wget https://www.ubuntulinux.jp/sources.list.d/precise.list -O /etc/apt/sources.list.d/ubuntu-ja.list
sudo apt-get update

# set locale
sudo su
echo en_US.UTF-8 UTF-8 >> /etc/locale.gen
aptitude -y install language-pack-ja-base language-pack-ja
update-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"
LC_COUNT=`grep -c -e LC_ALL=ja_JP.UTF-8 /etc/default/locale` 
#if test $LC_COUNT -eq 0 ; then
  echo "LC_ALL=ja_JP.UTF-8" >> /etc/default/locale
fi
locale-gen
dpkg-reconfigure locales
exit

# vim
ln -s Settings/vim/.vimrc .vimrc
ln -s Settings/vim/.vim .vim
mkdir ~/.vimswap
mkdir ~/.vimbackup
sudo apt-get install vim
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

# zsh
sudo apt-get install zsh
shpath=$(which zsh) 
chsh -s ${shpath}
ln -s Settings/zsh/.zshrc .zshrc
ln -s Settings/zsh/.zshenv .zshenv
ln -s Settings/zsh/.zsh_history .zsh_history
ln -s Settings/networK/satnet satnet
ln -s Settings/networK/fukudanet fukudanet
