# Copyright 2011 jim.foltz@gmail.com
#
# $Id$
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

require 'sketchup'
require 'extensions'

module JF
    module FreeDXF
        VERSION = "0.57"
    end
end

ext = SketchupExtension.new("FreeDXF", File.dirname(__FILE__)+"/freedxf/freedxf.rb")
ext.description = "FreeDXF v#{JF::FreeDXF::VERSION} - a .dxf file importer for SketchUp."
ext.creator     = "Jim Foltz <jim.foltz@gmail.com"
ext.copyright   = "2011 Jim Foltz"
ext.version     = ""
Sketchup.register_extension(ext, true)
